# Basic
title: 濤声依旧
subtitle: 面朝大海，春暖花开
welcome_message: 友情链接：<a href="https://www.wind23.com" target="_blank">Wind23</a>
description: 涛儿的心灵休憩小站
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
# highlighter: blue

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog
    

# Navigation buttons in the front page.
nav:
    # - {title: Back, description: Back to cover, url: 'https://www.teaur.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: teaur
    # duoshuo: 
    
# Social
social:
    weibo: 濤声若梦
    github: taotao568685
    twitter: taotao568685
    gplus: 114482989629457446257
    mail: taotao568685@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
